### ISSUE TITLE
Add the ability to pass false or null into props.buttons and clickable rows

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#15]
I am currently working on a project that uses this package, within the project we do not want buttons on the end of the table and we want the row itself to be clickable.

Currently you have to pass an empty array to not have any buttons. I believe that it should allow false or null (or a falsey statement).
```jsx
<DynamicDataTable
    rows={users}
    buttons={[]}
    dataItemManipulator={this.handleDataManipulation}
/>
```

I'd also like to see a `onRowClick` prop or similar that allows an action when a row gets clicked.

Perhaps I'll look into this?

**Comment by DivineOmega** [comment]
Sounds good on both records.

Would you mind separating these out into two issues please?
