### ISSUE TITLE
`AjaxDynamicDataTable` `axios` prop

### ISSUE THREAD

**Issue by DivineOmega** [langleyfoxall/react-dynamic-data-table#19]
A problem developers may encounter with using the `AjaxDynamicDataTable` component is that it currently uses its own `axios` instance, meaning it will not contain any authentication headers that may be required to access the API route.

One thought we had to combat this was to let people pass through an `axios` instance as prop. This should be optional, and default to the current behaviour.

Example syntax:

```jsx
<AjaxDynamicDataTable apiUrl={'/api/users/data-table'} axios={window.axios} />
```

**Comment by dextermb** [comment]
This would be interesting... to pass a new instance of axios into the component, or use window by default.

**Comment by DivineOmega** [comment]
I mentioned it should probably keep to the current behaviour if the prop is not passed.
