### ISSUE TITLE
Add prop for empty state rendering

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#20]
I think that it would be nice to have a prop named something along the lines of `emptyStateRender` which would allow you to pass in a:
- Function
- Element
- String

If a function or element is passed then it should return those rather than showing the table with "no data", if a string is passed then it'd just change the empty message.

Thoughts?

cc @NilesB @DivineOmega @JacobBrassington @wheatleyjj

**Comment by DivineOmega** [comment]
@dextermb There is a prop called `noDataMessage` that does what you request, if passed a string. It is currently undocumented (#2).

It does not support being passed a function or element (component?).

**Comment by dextermb** [comment]
@DivineOmega Nice. Yeah a valid react element (`React.isValidElement`) would be a nice option to have

**Comment by DivineOmega** [comment]
@dextermb Perhaps have a separate `noDataComponent` prop that replaces the table if present?

**Comment by dextermb** [comment]
> @dextermb Perhaps have a separate `noDataComponent` prop that replaces the table if present?

Maybe `emptyState`?

**Comment by DivineOmega** [comment]
`state` perhaps isn't the best term to use, due to possible confusion with React Component state.
