### ISSUE TITLE
Add custom row render function prop

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#25]
I'd like to see a custom row rendering function added. This way we would be able to tweak the rows with endless customization.

```jsx
renderRow(row) {
    return (
        <tr />
    );
}

<DynamicDataTable
    rows={users}
    rowRenderer={this.renderRow}
/>
```

The `rowRender` prop would accept a function that will have an instance of `row` passed back into it. It would then return a `React.isValidElement`, ideally a `tr`.

I'm up for implementing this. Anything else that it should do?

cc @NilesB @DivineOmega

**Comment by DivineOmega** [comment]
@DivineOmega Looks good. I'd stick with `rowRenderer` as the prop, rather than `rowRender`.

**Comment by wheatleyjj** [comment]
Might be worth mentioning looking at the datatables implementation - I remember it was pretty easy to use and very helpful:

https://datatables.net/examples/advanced_init/column_render.html <- I think this was it

**Comment by dextermb** [comment]
> @DivineOmega Looks good. I'd stick with `rowRenderer` as the prop name, rather than `rowRender`.

Definitely!
