### ISSUE TITLE
Update imports

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#28]
Currently when I go to use the AJAX table I have to import with:
```jsx
import AjaxDynamicDataTable from "@langleyfoxall/react-dynamic-data-table/dist/AjaxDynamicDataTable";
```

I'd like to see something like:
```jsx
import { AjaxDynamicDataTable } from '@langleyfoxall/react-dynamic-data-table';
```

Where the default import would be the normal dynamic datatable:
```jsx
import DynamicDataTable from '@langleyfoxall/react-dynamic-data-table';
```

But you could also import it through an object:
```jsx
import { DynamicDataTable, AjaxDynamicDataTable } from '@langleyfoxall/react-dynamic-data-table';
```

This could be achieved by having a file, other than the DynamicDataTable, as the `main` property in the `package.json`.

Thoughts?

**Comment by DivineOmega** [comment]
Agreed. Definitely sounds like a good idea.

**Comment by dextermb** [comment]
This has been [implemented](https://github.com/langleyfoxall/react-dynamic-data-table/commit/4c23a7d17f420ca2ca2c769b59e974341dbd80be)
