### ISSUE TITLE
Add `columnWidths` prop

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#29]
The `columnWidths` prop would be used to specify [`width`](https://html.com/attributes/td-width/) HTML attribute on `<th>` elements, which would then force all `<td>` to conform to the width.

```jsx
<DynamicDataTable
    rows={this.state.users}
    columnWidths={[50, 20, 30]}
/>
```

This could be easily implemented by looping through the columns and then checking the index in the `columnWidths` array.

I could see a use case for this where a table only have two columns, currently the table would be split in half. But say one column is `id` and the other `name`, the `id` could should be the smallest.

Thoughts?

cc @NilesB @DivineOmega

**Comment by dextermb** [comment]
@NilesB raised a point about what if the column widths go over `100` in total, luckily for us the widths get scaled, [here's a demo](https://codepen.io/anon/pen/PxaMZN).

**Comment by DivineOmega** [comment]
Have you considered what to do if you do not want to specify a column's width in the middle of the table?

Maybe something similar to the following.

```php
<DynamicDataTable
    rows={this.state.users}
    columnWidths={[10, 50, null, 10]}
/>
```

**Comment by dextermb** [comment]
> Have you considered what to do if you do not want to specify a column's width in the middle of the table?
> 
> Maybe something similar to the following.
> 
> ```
> <DynamicDataTable
>     rows={this.state.users}
>     columnWidths={[10, 50, null, 10]}
> />
> ```

I do prefer the array option, with using `null`. But it's worth raising this:
```jsx
<DynamicDataTable
    rows={this.state.users}
    columnWidths={{
        id: 10,
        name: 50,
    //  email: null
        address:10
    }}
/>
```

**Comment by DivineOmega** [comment]
@dextermb I much prefer this object format. 👍

**Comment by dextermb** [comment]
cc @NilesB @AlexCatch @wheatleyjj @JacobBrassington

**Comment by dextermb** [comment]
> @dextermb I much prefer this object format. 👍

Definitely more functional.

**Comment by JacobBrassington** [comment]
Firstly i am assuming that the key's of the object would correspond to the column name? Secondly would this be in `px` or `%`?

cc @dextermb @DivineOmega

**Comment by DivineOmega** [comment]
@JacobBrassington Column names is correct, and I believe @dextermb was intended the values to be percentages.

**Comment by JacobBrassington** [comment]
It may be a good idea to make the table have an `overflow: scroll` on on the x axis for incase the user enters total values over 100%.

**Comment by dextermb** [comment]
> It may be a good idea to make the table have an `overflow: scroll` on on the x axis for incase the user enters total values over 100%.

We could do, but the default behaviour is that table cell widths scale. So if they go over 100% then it still works out the difference. [Here's the demo I posted further up](https://codepen.io/anon/pen/PxaMZN). Maybe we set the overflow as a prop

**Comment by DivineOmega** [comment]
@JacobBrassington That functionality could be provided as another prop either specific to this case, or via a general `style` prop.
