### ISSUE TITLE
Do not render an empty cell if no buttons are set

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#40]
Somewhat linked to #16. Currently if the `buttons` prop has no length it'll [render an empty cell](https://github.com/langleyfoxall/react-dynamic-data-table/blob/master/src/Components/DataRow.jsx#L65-L67), surely it should not render anything if nothing is passed.

Thoughts?

**Comment by DivineOmega** [comment]
Simply rendering nothing would result in an incorrectly structured table. Would alternative do you suggest?

**Comment by dextermb** [comment]
> Simply rendering nothing would result in an incorrectly structured table. Would alternative do you suggest?

What would be unstructured? Couldn't you compare both in `DynamicDataTable` and `DataRow` if buttons are passed, then remove the trailing cell in the `thead` and `tbody`? Then you'd also check for `actions` in a similar fashion
