### ISSUE TITLE
Update defaultProps for `buttons` on DataTable

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/react-dynamic-data-table#82]
Default value for `buttons` prop on the DataTable needs to be updated to have the event as the first argument.

https://github.com/langleyfoxall/react-dynamic-data-table/blob/6b539d9c9f179685336ccffe954012e7d6decf9d/src/DynamicDataTable.jsx#L597

https://github.com/langleyfoxall/react-dynamic-data-table/blob/6b539d9c9f179685336ccffe954012e7d6decf9d/src/Components/DataRow.jsx#L172

**Comment by reegoram** [comment]
Hello @dextermb,
I'd like to work on this,

**Comment by reegoram** [comment]
I took that approach (#83), but I don't know whether is possible to restrict the callback functions to be always a two param function with event as the first one; or if it is necessary.

I'm open to any comment or suggestion for improving. Thanks, :smile:
